# Generated by Django 5.0.3 on 2024-05-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0003_alter_userprofile_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="speciality",
        ),
    ]
