# Generated by Django 5.0.3 on 2024-05-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0004_remove_customuser_speciality"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskobjuserresult",
            name="text",
            field=models.TextField(
                default="asd", help_text="Для ответов юзера, которые связаны с вопросами по вводу ответа"
            ),
            preserve_default=False,
        ),
    ]
