# Generated by Django 5.0.3 on 2024-05-23 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_task_ordinal_number"),
        ("progress", "0005_taskobjuserresult_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskobjuserresult",
            name="task_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_results",
                to="courses.taskobject",
                verbose_name="Объект задачи",
            ),
        ),
    ]
