# Generated by Django 5.0.3 on 2024-05-28 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0007_userprofile_last_subscription_type"),
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="last_subscription_type",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="subscription.subscriptiontype"
            ),
        ),
    ]
