# Generated by Django 5.0.3 on 2024-05-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0008_alter_userprofile_last_subscription_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="last_subscription_date",
            field=models.DateField(null=True, verbose_name="Последний раз когда юзер оформилял подписку"),
        ),
    ]
