# Generated by Django 5.0.3 on 2024-05-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0009_alter_userprofile_last_subscription_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="is_autopay_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
