# Generated by Django 5.0.3 on 2024-06-04 09:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_task_ordinal_number"),
        ("progress", "0010_alter_userprofile_is_autopay_allowed"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntermediateUserSkills",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_chosen", models.DateField(default=django.utils.timezone.now)),
                ("skill", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="courses.skill")),
                (
                    "user_profile",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="progress.userprofile"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="chosen_skills",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="chosen_skills",
            field=models.ManyToManyField(
                related_name="profile_skills",
                through="progress.IntermediateUserSkills",
                to="courses.skill",
                verbose_name="Выбранные навыки",
            ),
        ),
    ]
