# Generated by Django 5.0.3 on 2024-06-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0011_intermediateuserskills_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="intermediateuserskills",
            unique_together={("user_profile", "date_chosen")},
        ),
    ]
