# Generated by Django 5.0.3 on 2024-06-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0012_alter_intermediateuserskills_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="geo_position",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.DateField(null=True),
        ),
    ]
