# Generated by Django 5.0.3 on 2024-09-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_alter_task_managers"),
        ("progress", "0013_remove_customuser_geo_position_alter_customuser_age"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="intermediateuserskills",
            unique_together={("user_profile", "date_chosen", "skill")},
        ),
    ]
