# Generated by Django 5.0.3 on 2024-10-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("progress", "0016_alter_intermediateuserskills_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bought_trial_subscription",
            field=models.BooleanField(
                default=False,
                help_text="Покупал ли пользователь пробную подписку до этого",
            ),
        ),
    ]
