# Generated by Django 5.0.3 on 2024-10-31 12:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0017_userprofile_bought_trial_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userweekstat",
            name="created",
        ),
        migrations.AddField(
            model_name="userskilldone",
            name="datetime_created",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата создания"),
        ),
        migrations.AddField(
            model_name="userweekstat",
            name="datetime_created",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата создания"),
        ),
    ]
