# Generated by Django 5.0.3 on 2024-12-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0019_useranswersattemptcounter"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskobjuserresult",
            name="correct_answer",
            field=models.BooleanField(
                default=True, help_text="Дан верный/не верный ответ на задание", verbose_name="Правильный ответ"
            ),
        ),
    ]
