# Generated by Django 5.0.3 on 2024-03-24 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskobjuserresult",
            name="user",
        ),
        migrations.RenameModel(
            old_name="User",
            new_name="UserTest",
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chosen_skills", models.ManyToManyField(to="courses.skill")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to="progress.usertest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="taskobjuserresult",
            name="user_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_obj_results",
                to="progress.userprofile",
            ),
        ),
    ]
