# Generated by Django 5.0.3 on 2024-04-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_activated",
            field=models.BooleanField(default=False, verbose_name="Оплатил ли юзер подписку"),
        ),
    ]
