# Generated by Django 5.0.3 on 2024-04-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="chosen_skills",
            field=models.ManyToManyField(
                blank=True, related_name="profile_skills", to="courses.skill", verbose_name="Выбранные навыки"
            ),
        ),
    ]
