# Generated by Django 5.0.3 on 2024-04-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0002_alter_userprofile_chosen_skills"),
        ("progress", "0002_userprofile_is_activated"),
    ]

    operations = []
