# Generated by Django 5.0.3 on 2024-03-24 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "progress",
            "0002_remove_taskobjuserresult_user_rename_user_usertest_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskobjuserresult",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_obj_results",
                to="progress.userprofile",
            ),
        ),
    ]
