# Generated by Django 5.0.3 on 2024-04-15 23:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("progress", "0003_merge_20240415_2303"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="is_activated",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_autopay_allowed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_subscription_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Последний раз когда юзер оформилял подписку"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="chosen_skills",
            field=models.ManyToManyField(
                related_name="profile_skills", to="courses.skill", verbose_name="Выбранные навыки"
            ),
        ),
    ]
