# Generated by Django 5.0.3 on 2024-03-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_task_level"),
        ("progress", "0003_alter_taskobjuserresult_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="chosen_skills",
            field=models.ManyToManyField(
                related_name="profile_skills", to="courses.skill"
            ),
        ),
    ]
