# Generated by Django 5.0.3 on 2024-03-25 19:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0003_alter_connectanswer_options_alter_infoslide_options_and_more",
        ),
        ("progress", "0004_alter_userprofile_chosen_skills"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskobjuserresult",
            options={
                "verbose_name": "Ответ пользователя на единицу задания",
                "verbose_name_plural": "Ответы пользователя на единицу задания",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="usertest",
            options={
                "verbose_name": "Пользователь (тестовая модель)",
                "verbose_name_plural": "Пользователи (тестовая модель)",
            },
        ),
        migrations.AlterField(
            model_name="taskobjuserresult",
            name="correctness",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
                verbose_name="Правильность ответа",
            ),
        ),
        migrations.AlterField(
            model_name="taskobjuserresult",
            name="points_gained",
            field=models.PositiveIntegerField(verbose_name="Набранные баллы"),
        ),
        migrations.AlterField(
            model_name="taskobjuserresult",
            name="task_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_results",
                to="courses.taskobject",
                verbose_name="Объект задачи",
            ),
        ),
        migrations.AlterField(
            model_name="taskobjuserresult",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_obj_results",
                to="progress.userprofile",
                verbose_name="Профиль пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="chosen_skills",
            field=models.ManyToManyField(
                related_name="profile_skills",
                to="courses.skill",
                verbose_name="Выбранные навыки",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles",
                to="progress.usertest",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="usertest",
            name="age",
            field=models.IntegerField(verbose_name="Возраст пользователя"),
        ),
        migrations.AlterField(
            model_name="usertest",
            name="first_name",
            field=models.CharField(max_length=30, verbose_name="Имя пользователя"),
        ),
        migrations.AlterField(
            model_name="usertest",
            name="last_name",
            field=models.CharField(max_length=30, verbose_name="Фамилия пользователя"),
        ),
        migrations.AlterField(
            model_name="usertest",
            name="specialization",
            field=models.CharField(
                max_length=40, verbose_name="Специальность пользователя"
            ),
        ),
    ]
