# Generated by Django 5.0.3 on 2024-03-27 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("files", "0009_userfile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfoSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True, related_name="info_slides", to="files.userfile"
                    ),
                ),
            ],
            options={
                "verbose_name": "Информационный слайд",
                "verbose_name_plural": "Информационные слайды",
            },
        ),
        migrations.CreateModel(
            name="QuestionConnect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                ("description", models.TextField(null=True)),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="connect_questions",
                        to="files.userfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос на соотношение",
                "verbose_name_plural": "Вопросы на соотношение",
            },
        ),
        migrations.CreateModel(
            name="ConnectAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("connect_left", models.CharField(max_length=50)),
                ("connect_right", models.CharField(max_length=50)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connect_answers",
                        to="questions.questionconnect",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ для вопроса на соотношение",
                "verbose_name_plural": "Ответы для вопроса на соотношение",
            },
        ),
        migrations.CreateModel(
            name="QuestionSingleAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                ("description", models.TextField(null=True)),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True, related_name="single_questions", to="files.userfile"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос с одним правильным ответов",
                "verbose_name_plural": "Вопросы с одним правильным ответов",
            },
        ),
        migrations.CreateModel(
            name="SingleAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="single_answers",
                        to="questions.questionsingleanswer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ для вопроса с одним правильным ответом",
                "verbose_name_plural": "Ответы для вопроса с одним правильным ответом",
            },
        ),
    ]
