version: '3.9'

services:
  web:
    container_name: skills_web
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command:  bash ./scripts/startup_dev.sh
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
    volumes:
      - static-volume:/procollab/static
      - .:/procollab

  nginx:
    container_name: skills_nginx
    restart: unless-stopped
    build: ./nginx
    depends_on:
      - web
    ports:
      - 8001:80


  redis:
    container_name: skills_redis
    restart: unless-stopped
    image: redis:latest
    expose:
      - 6379
    volumes:
      - redis-data:/data
    depends_on:
      - web

  celerys:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    command: bash ./scripts/celery.sh
    #command: ls -la
    depends_on:
      - redis
      - web
    volumes:
       - .:/procollab

 # db: # не удалять нужно для тестов celery
#    container_name: skills_db
#    image: postgres
#    environment:
#      POSTGRES_DB: postgres
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - 5432:5432
#    restart: always
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/


volumes:
  redis-data:
  static-volume:
  #postgres_data: # не удалять нужно для тестов celery
