version: '3.9'

services:
  web:
    image: ghcr.io/procollab-github/skills_api:latest
    restart: always
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
    expose:
      - 8000

  nginx:
    build: ./nginx
    depends_on:
      - web
    ports:
      - 8001:80

  redis:
    image: redis:latest
    expose:
      - 6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
