version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0

  nginx:
    build: ./nginx
    depends_on:
      - web
    ports:
      - 8001:80

  redis:
    image: redis:latest
    expose:
      - 6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
