# Generated by Django 5.0.3 on 2024-05-09 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_initial"),
        ("progress", "0004_remove_customuser_speciality"),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ConnectAnswer",
            new_name="AnswerConnect",
        ),
        migrations.RenameModel(
            old_name="SingleAnswer",
            new_name="AnswerSingle",
        ),
        migrations.AlterField(
            model_name="questionconnect",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="questionsingleanswer",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="QuestionWrite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("files", models.ManyToManyField(blank=True, related_name="write_questions", to="files.filemodel")),
            ],
            options={
                "verbose_name": "Вопрос на ввод ответа",
                "verbose_name_plural": "Вопросы на ввод ответа",
            },
        ),
        migrations.CreateModel(
            name="AnswerUserWrite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="write_answer_results",
                        to="progress.userprofile",
                        verbose_name="Профиль пользователя",
                    ),
                ),
                (
                    "write_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="write_answers",
                        to="questions.questionwrite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ пользователя для вопроса с текстом",
                "verbose_name_plural": "Ответы пользователя для вопросы с текстом",
                "unique_together": {("write_question", "user_profile")},
            },
        ),
    ]
