# Generated by Django 5.0.3 on 2024-05-11 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_initial"),
        ("questions", "0002_rename_connectanswer_answerconnect_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerconnect",
            name="file_left",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connect_answers_withimages_left",
                to="files.filemodel",
                verbose_name="Вопрос (Картинка)",
            ),
        ),
        migrations.AddField(
            model_name="answerconnect",
            name="file_right",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connect_answers_withimages_right",
                to="files.filemodel",
                verbose_name="Ответ (Картинка)",
            ),
        ),
        migrations.AlterField(
            model_name="answerconnect",
            name="connect_left",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Вопрос (текст)"),
        ),
        migrations.AlterField(
            model_name="answerconnect",
            name="connect_right",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Ответ (текст)"),
        ),
    ]
