# Generated by Django 5.0.3 on 2024-06-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_alter_questionsingleanswer_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerconnect",
            name="connect_left",
            field=models.TextField(blank=True, max_length=450, null=True, verbose_name="Вопрос (текст)"),
        ),
        migrations.AlterField(
            model_name="answerconnect",
            name="connect_right",
            field=models.TextField(blank=True, max_length=450, null=True, verbose_name="Ответ (текст)"),
        ),
    ]
