# Generated by Django 5.0.3 on 2024-10-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_alter_answerconnect_connect_left_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="infoslide",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionconnect",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionsingleanswer",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionwrite",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
