# Generated by Django 5.0.3 on 2024-10-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_infoslide_video_url_questionconnect_video_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="infoslide",
            name="title",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
