# Generated by Django 5.0.3 on 2024-11-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0008_alter_infoslide_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionconnect",
            name="text",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="questionsingleanswer",
            name="text",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="questionwrite",
            name="text",
            field=models.TextField(max_length=100),
        ),
    ]
