# Generated by Django 5.0.3 on 2024-11-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0009_alter_questionconnect_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionconnect",
            name="text",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="questionsingleanswer",
            name="text",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="questionwrite",
            name="text",
            field=models.CharField(max_length=100),
        ),
    ]
