# Generated by Django 5.0.3 on 2024-11-25 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0010_alter_questionconnect_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionconnect",
            name="attempts_after_hint",
            field=models.SmallIntegerField(
                blank=True,
                help_text="Количество попыток после подсказки",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="questionconnect",
            name="attempts_before_hint",
            field=models.SmallIntegerField(
                blank=True,
                help_text="Количество попыток до показа подсказки",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="questionconnect",
            name="hint_text",
            field=models.TextField(blank=True, help_text="Текст подсказки", null=True),
        ),
        migrations.AddField(
            model_name="questionsingleanswer",
            name="attempts_after_hint",
            field=models.SmallIntegerField(
                blank=True,
                help_text="Количество попыток после подсказки",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="questionsingleanswer",
            name="attempts_before_hint",
            field=models.SmallIntegerField(
                blank=True,
                help_text="Количество попыток до показа подсказки",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="questionsingleanswer",
            name="hint_text",
            field=models.TextField(blank=True, help_text="Текст подсказки", null=True),
        ),
    ]
