# Generated by Django 5.0.3 on 2024-12-11 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0011_questionconnect_attempts_after_hint_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="infoslide",
            old_name="text",
            new_name="description",
        ),
    ]
