# Generated by Django 5.0.3 on 2025-06-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0014_alter_questionconnect_attempts_after_hint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answersingle",
            name="text",
            field=models.CharField(max_length=150),
        ),
    ]
