# Generated by Django 5.0.3 on 2024-05-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Название навыка")),
                ("description", models.TextField(null=True)),
                ("who_created", models.CharField(max_length=50, verbose_name="Кто создал")),
                ("quantity_of_levels", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("level", models.IntegerField(default=1, verbose_name="Уровень")),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
        migrations.CreateModel(
            name="TaskObject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "ordinal_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Если не указать, то автоматически станет последним в порядке показа",
                        null=True,
                        verbose_name="Порядковый номер",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="ID единицы задачи")),
            ],
            options={
                "verbose_name": "Часть задачи",
                "verbose_name_plural": "Части задачи",
            },
        ),
    ]
