# Generated by Django 5.0.3 on 2024-05-06 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("courses", "0001_initial"),
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill",
                to="files.filemodel",
                verbose_name="Картинка",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="courses.skill",
                verbose_name="Навык",
            ),
        ),
        migrations.AddField(
            model_name="taskobject",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_objects_content",
                to="contenttypes.contenttype",
                verbose_name="Тип единицы задачи",
            ),
        ),
        migrations.AddField(
            model_name="taskobject",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_objects",
                to="courses.task",
                verbose_name="Задача",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskobject",
            unique_together={("task", "ordinal_number")},
        ),
    ]
