# Generated by Django 5.0.3 on 2024-05-08 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_skill_file"),
        ("files", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="skill",
                to="files.filemodel",
                verbose_name="Картинка",
            ),
        ),
    ]
