# Generated by Django 5.0.3 on 2024-05-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_skill_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="ordinal_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Если не указать, то автоматически станет последним в порядке показа",
                null=True,
                verbose_name="Порядковый номер",
            ),
        ),
    ]
