# Generated by Django 5.0.3 on 2024-06-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_skill_status"),
        ("files", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="skill_point_logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="skill_point_logo",
                to="files.filemodel",
                verbose_name="Лого навыка в строке прогресса",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="skill_preview",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="skill_preview",
                to="files.filemodel",
                verbose_name="Лого навыка в уровне",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="skill",
                to="files.filemodel",
                verbose_name="Основоное лого",
            ),
        ),
    ]
