# Generated by Django 5.0.3 on 2024-06-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_popup_taskobject_popup"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("draft", "Черновик"), ("published", "Опубликован")],
                default="draft",
                max_length=15,
                verbose_name="Статус",
            ),
        ),
    ]
