# Generated by Django 5.0.3 on 2024-06-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskobject",
            name="validate_answer",
            field=models.BooleanField(default=True, verbose_name="Проверять ответ на вопрос?"),
        ),
    ]
