# Generated by Django 5.0.3 on 2024-07-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_taskobject_validate_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="week",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1 Неделя"), (2, "2 Неделя"), (3, "3 Неделя"), (4, "4 Неделя (До конца месяца)")],
                default=1,
                verbose_name="Неделя",
            ),
        ),
        migrations.AlterField(
            model_name="taskobject",
            name="validate_answer",
            field=models.BooleanField(
                default=True,
                help_text="Отключает проверку ответа.<br>(Только для 'Вопрос с одним правильным ответом', 'Вопрос с одним правильным ответом (Исключающий)' и 'Вопрос на соотношение', на остальных проверка не требуется)",
                verbose_name="Проверка ответа",
            ),
        ),
    ]
