# Generated by Django 5.0.3 on 2024-09-30 18:58

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_task_week_alter_taskobject_validate_answer"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="task",
            managers=[
                ("available", django.db.models.manager.Manager()),
            ],
        ),
    ]
