# Generated by Django 5.0.3 on 2024-09-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_alter_task_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="task",
            managers=[],
        ),
    ]
