# Generated by Django 5.0.3 on 2024-11-06 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_alter_skill_status_alter_task_status"),
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="subcription_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Минимальный тип подписки, с которой навык становится доступен",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="subscription.subscriptiontype",
                verbose_name="Тип подписки",
            ),
        ),
    ]
