# Generated by Django 5.0.3 on 2024-12-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_skill_subcription_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="free_access",
            field=models.BooleanField(
                default=False, help_text="Возможность проходить без подписки.", verbose_name="Доступ бесплатно"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="free_access",
            field=models.BooleanField(
                default=False, help_text="Возможность проходить без подписки.", verbose_name="Доступ бесплатно"
            ),
        ),
    ]
