# Generated by Django 5.0.3 on 2025-04-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_skill_is_from_trajectory_skill_requires_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="free_access",
            field=models.BooleanField(
                default=True, help_text="Возможность проходить без подписки.", verbose_name="Доступ бесплатно"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="free_access",
            field=models.BooleanField(
                default=True, help_text="Возможность проходить без подписки.", verbose_name="Доступ бесплатно"
            ),
        ),
    ]
