# Generated by Django 5.0.3 on 2024-03-27 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название навыка"),
                ),
            ],
            options={
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("level", models.IntegerField(default=1, verbose_name="Уровень")),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="courses.skill",
                        verbose_name="Навык",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
        migrations.CreateModel(
            name="TaskObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordinal_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Если не указать, то автоматически станет последним в порядке показа",
                        null=True,
                        verbose_name="Порядковый номер",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(verbose_name="ID единицы задачи"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_objects_content",
                        to="contenttypes.contenttype",
                        verbose_name="Тип единицы задачи",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_objects",
                        to="courses.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Часть задачи",
                "verbose_name_plural": "Части задачи",
                "unique_together": {("task", "ordinal_number")},
            },
        ),
    ]
