# Generated by Django 5.0.3 on 2024-03-25 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("courses", "0002_alter_task_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="connectanswer",
            options={
                "verbose_name": "Вопрос на соотношение",
                "verbose_name_plural": "Вопросы на соотношение",
            },
        ),
        migrations.AlterModelOptions(
            name="infoslide",
            options={
                "verbose_name": "Информационный слайд",
                "verbose_name_plural": "Информационные слайды",
            },
        ),
        migrations.AlterModelOptions(
            name="questionconnect",
            options={
                "verbose_name": "Вопрос на соотношение",
                "verbose_name_plural": "Вопросы на соотношение",
            },
        ),
        migrations.AlterModelOptions(
            name="questionsingleanswer",
            options={
                "verbose_name": "Вопрос с одним правильным ответов",
                "verbose_name_plural": "Вопросы с одним правильным ответов",
            },
        ),
        migrations.AlterModelOptions(
            name="singleanswer",
            options={
                "verbose_name": "Ответ для вопроса с одним правильным ответом",
                "verbose_name_plural": "Ответы для вопроса с одним правильным ответом",
            },
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"verbose_name": "Навык", "verbose_name_plural": "Навыки"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Задача", "verbose_name_plural": "Задачи"},
        ),
        migrations.AlterModelOptions(
            name="taskobject",
            options={
                "verbose_name": "Часть задачи",
                "verbose_name_plural": "Части задачи",
            },
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название навыка"),
        ),
        migrations.AlterField(
            model_name="task",
            name="level",
            field=models.IntegerField(default=1, verbose_name="Уровень"),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="task",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="courses.skill",
                verbose_name="Навык",
            ),
        ),
        migrations.AlterField(
            model_name="taskobject",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_objects_content",
                to="contenttypes.contenttype",
                verbose_name="Тип единицы задачи",
            ),
        ),
        migrations.AlterField(
            model_name="taskobject",
            name="object_id",
            field=models.PositiveIntegerField(verbose_name="ID единицы задачи"),
        ),
        migrations.AlterField(
            model_name="taskobject",
            name="ordinal_number",
            field=models.PositiveSmallIntegerField(
                null=True, verbose_name="Порядковый номер"
            ),
        ),
        migrations.AlterField(
            model_name="taskobject",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_objects",
                to="courses.task",
                verbose_name="Задача",
            ),
        ),
    ]
