# Generated by Django 5.0.3 on 2024-03-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0003_alter_connectanswer_options_alter_infoslide_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infoslide",
            name="files",
        ),
        migrations.RemoveField(
            model_name="questionconnect",
            name="files",
        ),
        migrations.RemoveField(
            model_name="questionsingleanswer",
            name="files",
        ),
        migrations.RemoveField(
            model_name="singleanswer",
            name="question",
        ),
        migrations.AlterField(
            model_name="taskobject",
            name="ordinal_number",
            field=models.PositiveSmallIntegerField(
                help_text="Если не указать, то автоматически станет последним в порядке показа",
                null=True,
                verbose_name="Порядковый номер",
            ),
        ),
        migrations.DeleteModel(
            name="ConnectAnswer",
        ),
        migrations.DeleteModel(
            name="InfoSlide",
        ),
        migrations.DeleteModel(
            name="QuestionConnect",
        ),
        migrations.DeleteModel(
            name="QuestionSingleAnswer",
        ),
        migrations.DeleteModel(
            name="SingleAnswer",
        ),
    ]
