# Generated by Django 5.0.3 on 2024-03-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0004_remove_infoslide_files_remove_questionconnect_files_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskobject",
            name="ordinal_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Если не указать, то автоматически станет последним в порядке показа",
                null=True,
                verbose_name="Порядковый номер",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskobject",
            unique_together={("task", "ordinal_number")},
        ),
    ]
