# Generated by Django 5.0.3 on 2024-03-23 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0007_auto_20230929_1727"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfile",
            name="user",
        ),
    ]
