# Generated by Django 5.0.3 on 2025-04-03 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptiontype",
            name="features",
            field=models.TextField(
                help_text="Каждый пункт писать через запятую",
                null=True,
                verbose_name="Что пользователь получит за подписку",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptiontype",
            name="name",
            field=models.CharField(
                choices=[("Start", "Start"), ("PRO", "PRO"), ("PRO+", "PRO+")],
                max_length=30,
                unique=True,
                verbose_name="Название подписки",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptiontype",
            name="price",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)], verbose_name="Стоимость подписки"
            ),
        ),
    ]
