# Generated by Django 5.0.3 on 2025-04-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0002_alter_subscriptiontype_features_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontype",
            name="subscription_level",
            field=models.CharField(
                choices=[("Start", "Start"), ("PRO", "PRO"), ("PRO+", "PRO+")],
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Уровень подписки",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptiontype",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Название подписки"),
        ),
    ]
