# Generated by Django 5.0.3 on 2024-05-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileModel",
            fields=[
                ("link", models.URLField(primary_key=True, serialize=False)),
                ("datetime_uploaded", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField(default="file")),
                ("extension", models.TextField(blank=True, default="")),
                ("mime_type", models.CharField(default="", max_length=256)),
                ("size", models.PositiveBigIntegerField(blank=True, default=1)),
            ],
            options={
                "verbose_name": "Файл",
                "verbose_name_plural": "Файлы",
                "ordering": ["datetime_uploaded"],
            },
        ),
    ]
