name: 'Deploy dev server'

on:
  push:
    branches: 
      - dev

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: run on server
          uses: garygrossgarten/github-action-ssh@release
          with:
            host: ${{ secrets.DEV_SERVER_HOST }}
            username: ${{ secrets.DEV_SERVER_USER }}
            password: ${{ secrets.DEV_SERVER_PASSWORD }}
            command: |
              cd /root/skills_api &&
              git checkout dev &&
              git pull &&
              
              rm -f .env &&
              touch .env &&
              
              echo "DJANGO_SECRET_KEY=${{ secrets.DEV_DJANGO_SECRET_KEY }}" >> .env &&
              
              echo "DATABASE_NAME=${{ secrets.DEV_DATABASE_NAME }}" >> .env &&
              echo "DATABASE_PASSWORD=${{ secrets.DEV_DATABASE_PASSWORD }}" >> .env &&
              echo "DATABASE_USER=${{ secrets.DEV_DATABASE_USER }}" >> .env &&
              echo "DATABASE_HOST=${{ secrets.DEV_DATABASE_HOST }}" >> .env &&
              echo "DATABASE_PORT=${{ secrets.DEV_DATABASE_PORT }}" >> .env &&
            
              echo "SELECTEL_ACCOUNT_ID=${{ secrets.SELECTEL_ACCOUNT_ID }}" >> .env &&
              echo "SELECTEL_CONTAINER_NAME=${{ secrets.SELECTEL_CONTAINER_NAME }}" >> .env &&
              echo "SELECTEL_CONTAINER_PASSWORD=${{ secrets.SELECTEL_CONTAINER_PASSWORD }}" >> .env &&
              echo "SELECTEL_CONTAINER_USERNAME=${{ secrets.SELECTEL_CONTAINER_USERNAME }}" >> .env &&
                         
              docker-compose -f docker-compose.dev-ci.yml up -d --build --force-recreate
