name: Django CI

on:
  push:
    branches:
      - '**'

jobs:
  django-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root

      - name: Run tests
        run: |
          cd apps/
          poetry run pytest
        env:
          DEBUG: True
          USE_SQLITE: True
